apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-service-deployment
  labels:
    app: url-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url-service
  template:
    metadata:
      labels:
        app: url-service
    spec:
      containers:
        - name: url-service
          image: developerdavo/url-shortener2
          ports:
            - containerPort: 8081
              name: url-service
---
apiVersion: v1
kind: Service
metadata:
  name: url-service-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: url-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: url-service
      nodePort: 30100