apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-db-deployment
  labels:
    app: url-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-db
  template:
    metadata:
      labels:
        app: url-db
    spec:
      containers:
        - name: url-db
          image: mongo:5.0
          ports:
          - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: url-db-service
spec:
  selector:
    app: url-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
